//
// Created by Made on 03/05/2025.
//

#ifndef SYNTH_ERRNO_H
#define SYNTH_ERRNO_H

#include <limits.h>
#include <types.h>

#define SERR_PAGE_LEN 100

typedef enum
{
    SERR_OK,

    SERR_SOLFEGE_BAD_ACCIDENTAL = SERR_PAGE_LEN * 0,
    SERR_SOLFEGE_INVALID_NOTE,

    SERR_SFS_INVALID_SAMPLERATE = SERR_PAGE_LEN * 1,
    SERR_SFS_INVALID_LOOP_PRESET,
    SERR_SFS_INVALID_SOUNDTYPE,
    SERR_SFS_VELOCITY_COUNT_EXCEEDED,
    SERR_SFS_INVALID_VELOCITY,

    SERR_CMD_INVALID_ARGUMENT = SERR_PAGE_LEN * 2,

    SERR_SD_GENERIC_ERROR = SERR_PAGE_LEN * 3,
    SERR_SD_READ_ERROR,
    SERR_SD_WRITE_ERROR,
    SERR_SD_FATAL_ERROR,

    SERR_GENERIC_ERROR = SERR_PAGE_LEN * 4,
} synthErrno;

void synthPanic(synthErrno pCode);

#endif //SYNTH_ERRNO_H
